Token: "BOT_TOKEN"
BotName: "ELicenses"
GuildID: "GUILD_ID"
EmbedColors: "#5e99ff"
LogCommands: false
Statistics: true
MongoURI: "CONNECTION_URL"

BotActivitySettings:
  Enabled: true
  Type: "WATCHING"
  Interval: 30
  Statuses:
    - "{total-licenses} licenses"
    - "{total-users} users"

WebServerSettings:
  Port: 3000
  ApiKey: "API_KEY"

LicenseSettings:
  IPCap: 0
  HWIDCap: 0
  RequireBuiltByBitUserID: true
  GiveCustomerRole: true
  CustomerRoleOnJoin: true
  Characters: "ABCDEFGHIJKLMNIOPQRSTUVWXYZ0123456789"

EmbedSettings:
  Color: "#5e99ff"
  Title: ""
  AuthorName: "Your License Key"
  AuthorIcon: "default"
  Description: "Sharing this key with anyone will result in your license being **permanently** disabled and your access to the product **removed**."
  Fields:
    - Name: "Product"
      Value: "{product}"
    - Name: "License Key"
      Value: "```{licenseKey}```"

RatelimitSettings:
  Enabled: true
  MaxRequests: 15
  Time: 3

WebhookLogsSettings:
  Enabled: true
  AuthenticationWebhookURL: "WEBHOOK_URL"
  CommandsWebhookURL: "WEBHOOK_URL"

getLicense:
  Enabled: true

license_create:
  Enabled: true
  AllowedRoles: ["ROLE_ID"]

license_delete:
  Enabled: true
  AllowedRoles: ["ROLE_ID"]

license_list:
  Enabled: true
  AllowedRoles: ["ROLE_ID"]

license_get:
  Enabled: true
  AllowedRoles: ["ROLE_ID"]

license_cleardata:
  Enabled: true
  AllowedRoles: ["ROLE_ID"]

product_create:
  Enabled: true
  AllowedRoles: ["ROLE_ID"]

product_delete:
  Enabled: true
  AllowedRoles: ["ROLE_ID"]

product_list:
  Enabled: true
  AllowedRoles: ["ROLE_ID"]

Locale:
  NoPermsMessage: "Sorry, you don't have permissions to use this command!"

DevMode: true