# MongoDB configuration
mongo:
  uri: "mongodb://localhost:27017/licenses" # Replace with your MongoDB URI

# Discord configuration
discord:
  token: "YOUR_DISCORD_BOT_TOKEN" # Replace with your Discord bot token
  client_id: "YOUR_DISCORD_CLIENT_ID" # Replace with your Discord client ID
  guild_id: "YOUR_DISCORD_GUILD_ID" # Replace with your Discord guild ID

# Express server configuration
server:
  port: 3000 # Replace with your preferred port

# License settings
license:
  product_guides:
    product1: "Guide for product 1"
    product2: "Guide for product 2"

